name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the site in the jekyll/builder container
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll \
          -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: 65.0.11.11
          username: ec2-user  # Default username for Amazon Linux
          key: ${{ secrets.EC2_SSH_KEY }}  # Your private key stored in GitHub Secrets
          source: "_site/*"  # Source built Jekyll site
          target: "/var/www/html"  # Target directory on EC2
